blank_issues_enabled: true
contact_links:
  - name: test
    url: https://github.com/Dami-LEE00/issue_test
    about: test
  - name: test
    url: https://github.com/Dami-LEE00/issue_test
    about: test
